apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aap-deployment
  labels:
    app: myreplicaset
    type: fronted
spec:
  selector:
    matchLabels:
      app: mypod
      type: my-first-app
  replicas: 3
  strategy:
    type: RollingUpdate
    
  template:
    metadata:
      name: my-pod
      labels:
        app: mypod
        type: my-first-app
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.7
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30003
      name: test1
  selector:
    app: mypod
    type: my-first-app

  